"""add expires_at to api_tokens

Revision ID: 25e6a3f4703d
Revises: f9b2a4c6d8e3
Create Date: 2026-05-13 16:51:29.939911
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '25e6a3f4703d'
down_revision: Union[str, None] = 'f9b2a4c6d8e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_tokens', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_tokens', 'expires_at')
    # ### end Alembic commands ###
