"""add archived_at to projects

Revision ID: 2864d710f92c
Revises: c4696244fc13
Create Date: 2026-05-13 20:11:53.608235
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2864d710f92c'
down_revision: Union[str, None] = 'c4696244fc13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_projects_archived_at'), 'projects', ['archived_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_archived_at'), table_name='projects')
    op.drop_column('projects', 'archived_at')
    # ### end Alembic commands ###
