"""add allow_user_self_delete to settings

Revision ID: 320b81850a90
Revises: 2864d710f92c
Create Date: 2026-05-13 20:29:58.359597
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '320b81850a90'
down_revision: Union[str, None] = '2864d710f92c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('allow_user_self_delete', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'allow_user_self_delete')
    # ### end Alembic commands ###
