"""add app_settings singleton

Revision ID: 461099e5bde1
Revises: f481aa41654b
Create Date: 2026-05-07 23:28:18.909771
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '461099e5bde1'
down_revision: Union[str, None] = 'f481aa41654b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_url', sa.String(length=512), nullable=True),
    sa.Column('app_name', sa.String(length=64), server_default='Testjam', nullable=False),
    sa.Column('allow_registration', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('default_environment', sa.String(length=64), nullable=True),
    sa.Column('default_version_pattern', sa.String(length=64), nullable=True),
    sa.Column('max_upload_mb', sa.Integer(), server_default='20', nullable=False),
    sa.Column('notifications_retention_days', sa.Integer(), server_default='90', nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.String(length=255), nullable=True),
    sa.Column('smtp_from', sa.String(length=255), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("INSERT INTO app_settings (id, app_name, allow_registration, max_upload_mb, notifications_retention_days, smtp_use_tls) VALUES (1, 'Testjam', true, 20, 90, true)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
