"""enforce not null on api_tokens.created_at and execution_attachments.uploaded_at

Revision ID: 6598b2bb11e0
Revises: ad2d55a50ae5
Create Date: 2026-05-07 21:47:09.980972
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6598b2bb11e0'
down_revision: Union[str, None] = 'ad2d55a50ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("UPDATE api_tokens SET created_at = now() WHERE created_at IS NULL")
    op.execute("UPDATE execution_attachments SET uploaded_at = now() WHERE uploaded_at IS NULL")
    op.alter_column('api_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('execution_attachments', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('execution_attachments', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
