"""version release dates

Revision ID: 7a61b8d489ef
Revises: f0e1c5471297
Create Date: 2026-05-16 21:40:33.202399
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7a61b8d489ef'
down_revision: Union[str, None] = 'f0e1c5471297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_versions', sa.Column('release_date', sa.Date(), nullable=True))
    op.add_column('project_versions', sa.Column('released_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_versions', 'released_at')
    op.drop_column('project_versions', 'release_date')
    # ### end Alembic commands ###
