"""user timezone and use_relative_dates

Revision ID: 7b2bdd216691
Revises: 80b02498ca2d
Create Date: 2026-05-15 00:00:48.854537
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7b2bdd216691'
down_revision: Union[str, None] = '80b02498ca2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('use_relative_dates', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'use_relative_dates')
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###
