"""datetime utc aware

Revision ID: 80b02498ca2d
Revises: 320b81850a90
Create Date: 2026-05-14 23:03:22.134308
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '80b02498ca2d'
down_revision: Union[str, None] = '320b81850a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_tokens', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('api_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('app_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('attachments', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="uploaded_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('case_revisions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('execution_attachments', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="uploaded_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_members', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="added_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'archived_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="archived_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('result_attachments', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="uploaded_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_cases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_executions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('test_executions', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="finished_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('test_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_plans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_results', 'executed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="executed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('test_step_results', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('test_suites', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_suites', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'locked_until',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="locked_until AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="deleted_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="deleted_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('users', 'locked_until',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="locked_until AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('test_suites', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_suites', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_step_results', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('test_results', 'executed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="executed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('test_plans', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_plans', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_executions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_executions', 'finished_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="finished_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('test_executions', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('test_cases', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_cases', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('result_attachments', 'uploaded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="uploaded_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'archived_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="archived_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('projects', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_versions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_members', 'added_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="added_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('password_reset_tokens', 'used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('groups', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('execution_attachments', 'uploaded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="uploaded_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('case_revisions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('attachments', 'uploaded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="uploaded_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('app_settings', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('api_tokens', 'last_used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('api_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
