"""add lockout columns to users

Revision ID: c02821d14f90
Revises: 25e6a3f4703d
Create Date: 2026-05-13 17:37:15.850447
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c02821d14f90'
down_revision: Union[str, None] = '25e6a3f4703d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_count')
    # ### end Alembic commands ###
