"""add deleted_at to users

Revision ID: c4696244fc13
Revises: 7e267648907c
Create Date: 2026-05-13 19:59:12.864528
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c4696244fc13'
down_revision: Union[str, None] = '7e267648907c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_column('users', 'deleted_at')
    # ### end Alembic commands ###
