"""add_versions_setup_teardown_external_id_log_output

Revision ID: c8b52cb822a5
Revises: 2c8f888e9a1e
Create Date: 2026-05-03 09:11:24.241195
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c8b52cb822a5'
down_revision: Union[str, None] = '2c8f888e9a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('vcs_tag', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('test_cases', sa.Column('setup', sa.Text(), nullable=True))
    op.add_column('test_cases', sa.Column('teardown', sa.Text(), nullable=True))
    op.add_column('test_cases', sa.Column('external_id', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_test_cases_external_id'), 'test_cases', ['external_id'], unique=False)
    op.add_column('test_executions', sa.Column('version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test_executions', 'project_versions', ['version_id'], ['id'], ondelete='SET NULL')
    op.add_column('test_step_results', sa.Column('log_output', sa.Text(), nullable=True))
    op.add_column('test_steps', sa.Column('step_type', sa.String(length=16), nullable=True))
    op.execute("UPDATE test_steps SET step_type = 'action' WHERE step_type IS NULL")
    op.alter_column('test_steps', 'step_type', nullable=False)
    op.add_column('test_suites', sa.Column('setup', sa.Text(), nullable=True))
    op.add_column('test_suites', sa.Column('teardown', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_suites', 'teardown')
    op.drop_column('test_suites', 'setup')
    op.drop_column('test_steps', 'step_type')
    op.drop_column('test_step_results', 'log_output')
    op.drop_constraint(None, 'test_executions', type_='foreignkey')
    op.drop_column('test_executions', 'version_id')
    op.drop_index(op.f('ix_test_cases_external_id'), table_name='test_cases')
    op.drop_column('test_cases', 'external_id')
    op.drop_column('test_cases', 'teardown')
    op.drop_column('test_cases', 'setup')
    op.drop_table('project_versions')
    # ### end Alembic commands ###
