"""user locale

Revision ID: f0e1c5471297
Revises: e3c7d9b5f2a1
Create Date: 2026-05-16 20:44:16.639456
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f0e1c5471297'
down_revision: Union[str, None] = 'e3c7d9b5f2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locale')
    # ### end Alembic commands ###
