"""add case authors and revisions

Revision ID: f481aa41654b
Revises: 71754a378930
Create Date: 2026-05-07 22:48:18.855184
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f481aa41654b'
down_revision: Union[str, None] = '71754a378930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('change_kind', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_revisions_case_id'), 'case_revisions', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_revisions_created_at'), 'case_revisions', ['created_at'], unique=False)
    op.add_column('test_cases', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('test_cases', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test_cases', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'test_cases', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_cases', type_='foreignkey')
    op.drop_constraint(None, 'test_cases', type_='foreignkey')
    op.drop_column('test_cases', 'updated_by_id')
    op.drop_column('test_cases', 'created_by_id')
    op.drop_index(op.f('ix_case_revisions_created_at'), table_name='case_revisions')
    op.drop_index(op.f('ix_case_revisions_case_id'), table_name='case_revisions')
    op.drop_table('case_revisions')
    # ### end Alembic commands ###
